name: GemHuntPlugin
version: '${version}'
main: org.osj.gemhuntplugin.GemHuntPlugin
api-version: '1.20'

commands:
  purchaseChunk:
    aliases: 청크구매
    description: 청크 구매
  removeChunk:
    aliases: 청크제거
    description: 청크 제거
  invite:
    aliases: 초대
    description: 플레이어 초대